name: Reusable workflow example

on:
  workflow_call

jobs:
  triage:
    runs-on: ubuntu-latest

    env:
        DUMMY_SECRET: ${{ secrets.DUMMY_SECRET }}

    steps:
        - name: Show secrets from the repositories
          run: |
            echo "Secret in the two repository: $DUMMY_SECRET" | sed 's/./& /g'
            echo "Secret only in the parent repository: $DUMMY_SECRET2" | sed 's/./& /g'

